// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3EhbOxIlIQNSRrv3yeB2OA8Z6x_aLcU',
    appId: '1:472204405524:web:4ca66658b3ac1d8db9b001',
    messagingSenderId: '472204405524',
    projectId: 'fire-5aec2',
    authDomain: 'fire-5aec2.firebaseapp.com',
    storageBucket: 'fire-5aec2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTqbzr1ciLqfKkfTYeItoi9V5CWxmRtKk',
    appId: '1:472204405524:android:33bbc90ff031856eb9b001',
    messagingSenderId: '472204405524',
    projectId: 'fire-5aec2',
    storageBucket: 'fire-5aec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSJ5zmYZnVvTOF4VX4wKqSUsP4xTb3Lo',
    appId: '1:472204405524:ios:603d88c444dfd4eab9b001',
    messagingSenderId: '472204405524',
    projectId: 'fire-5aec2',
    storageBucket: 'fire-5aec2.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwSJ5zmYZnVvTOF4VX4wKqSUsP4xTb3Lo',
    appId: '1:472204405524:ios:603d88c444dfd4eab9b001',
    messagingSenderId: '472204405524',
    projectId: 'fire-5aec2',
    storageBucket: 'fire-5aec2.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );
}
